---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.costalong.com
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.costalong.com
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - apps.costalong.com
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
